name: Java CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-report:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - name: Run Unit Test
        run: mvn -B test --file pom.xml
      - name: Publish Surefire Test Report
        uses: ScaCap/action-surefire-report@v1.3.0


